const OFFICIAL_PHONE_DISPLAY = '0908 464 818';
const OFFICIAL_PHONE_DIGITS = '0908464818';
const OFFICIAL_ZALO_URL = `https://zalo.me/${OFFICIAL_PHONE_DIGITS}`;

module.exports = {
  OFFICIAL_PHONE_DISPLAY,
  OFFICIAL_PHONE_DIGITS,
  OFFICIAL_ZALO_URL,
};
